### PR TITLE
Added AI Chatbot

### PR DESCRIPTION
**Pull request by eiva078**
Fixes Issue No :- #16 

**Description**
This AI chatbot is based on the GPT-3.5 It can answer questions, offer information and provide 24/7 assistance, enhancing user experience through efficient and effective interactions. 

Screenshot 2024-05-31 012902

Screenshot 2024-05-31 012924

Screenshot 2024-05-31 012943

Requesting you to please label the PR before merging.

### CODE REVIEW

**Comment by subhadipbhowmik** [comment]
Looking very nice. Could You please rename style.css => style.css..

**Comment by subhadipbhowmik** [comment]
> Looking very nice. Could You please rename style.css => style.css..

Also provide a preview in /doc and /blog section

**Comment by eiva078** [comment]
> Looking very nice. Could You please rename style.css => style.css..

Sir its stylr.css....is it fine??

**Comment by subhadipbhowmik** [comment]
> > Looking very nice. Could You please rename style.css => style.css..
> 
> Sir its stylr.css....is it fine??

Have you changed the file name??

**Comment by eiva078** [comment]
> > > Looking very nice. Could You please rename style.css => style.css..
> > 
> > 
> > Sir its stylr.css....is it fine??
> 
> Have you changed the file name??

No sir

**Comment by subhadipbhowmik** [comment]
> > > Looking very nice. Could You please rename style.css => style.css..
> > 
> > 
> > Sir its stylr.css....is it fine??
> 
> Have you changed the file name??

Screenshot 2024-05-31 072325

**Comment by subhadipbhowmik** [comment]
Just Change the file name.. And also give an preview of ai chatbot in mobile view and in different section i.e /doc, /blog

**Comment by eiva078** [comment]
> > > > Looking very nice. Could You please rename style.css => style.css..
> > > 
> > > 
> > > Sir its stylr.css....is it fine??
> > 
> > 
> > Have you changed the file name??
> 
> Screenshot 2024-05-31 072325

I meant that I named it that way before to avoid any clashes with other names.

**Comment by subhadipbhowmik** [comment]
> > > > > Looking very nice. Could You please rename style.css => style.css..
> > > > 
> > > > 
> > > > Sir its stylr.css....is it fine??
> > > 
> > > 
> > > Have you changed the file name??
> > 
> > 
> > Screenshot 2024-05-31 072325
> 
> I meant that I named it that way before to avoid any clashes with other names.

Ok no problem.. Just give a try to change and then see what goes on. Check whether it is working perfectly or not.. And give an preview in /doc and /blog section.

**Comment by eiva078** [comment]
> Just Change the file name.. And also give an preview of ai chatbot in mobile view and in different section i.e /doc, /blog

Screenshot 2024-05-31 072741

Screenshot 2024-05-31 072802

 I have given max-width 450px after that it will cover full screen 
Screenshot 2024-05-31 072858

**Comment by subhadipbhowmik** [comment]
Awesome job. Just cehck for the last time whete it is working after renaming the file or nor. Then I am merging to the main branch.

**Pull request merged**
