### PR TITLE
Added topic constructors to day 12

### LINKED ISSUE #96: Add day 10 content
### Select the Day of Content

Day 10

### What information is missing?

I would like to add content on 'Constructors'. Kindly assign this issue to me under gssoc'24

### PR DESCRIPTION
**Pull request by pankhuri92**
Fix #96 
There are 4 subtopics to 'Constructors' that I have added.

Screenshot 2024-06-04 201117
Screenshot 2024-06-04 201159
Screenshot 2024-06-04 201219
Screenshot 2024-06-04 201230
Screenshot 2024-06-04 201253

### CODE REVIEW

**Comment by subhadipbhowmik** [comment]
Do not just copy and paste files. We are set on some rules. We have Till Day 11 Curricullam. We Will Extend After Some Days. Work On only one file at a time.

**Comment by pankhuri92** [comment]
Since putting all of the content in one file made it look monotonous, I split it into subparts - 'Introduction', 'Types', etc. Hence there are multiple files committed.

**Comment by pankhuri92** [comment]
Kindly review.

**Comment by pankhuri92** [comment]
@subhadipbhowmik please review my pr. It's been over a week.

**Comment by subhadipbhowmik** [comment]
> Work On only one file at a time.

Work On only one file at a time.

**Comment by pankhuri92** [comment]
@subhadipbhowmik Can you please elaborate on your point. Do you want me to put all the content under just one file? I can do that but then it won't be well categorised like this. It will become a single page of this long content.

**Pull request merged**
