### PR TITLE
[Docs]: Want to Add Folder which will Contain Different questions related to topic And their Solution #351

### PR DESCRIPTION
**Pull request by nishant0708**
Added a Practice_Question Folder Which consist of 3 category problems and their solution

### CODE REVIEW

**Comment by subhadipbhowmik** [comment]
Do not push node_modules folder

**Comment by nishant0708** [comment]
Okay I will delete it

**Comment by nishant0708** [comment]
hey @subhadipbhowmik  its should be good Now.

**Comment by nishant0708** [comment]
Hey @subhadipbhowmik can you review this pr..

**Pull request merged**
