### PR TITLE
Added Day 6

### PR DESCRIPTION
**Pull request by Abhishek0732**
I have added the OOPS concepts in day 6.

### CODE REVIEW

**Comment by subhadipbhowmik** [comment]
> I have added the OOPS concepts in day 6.

Brother, I am saying to add Content in The Existing Days.. Because After Completeing first 5 Days Content Then We Will Make Images and content for the next days.

**Comment by Abhishek0732** [comment]
Ok

**Comment by Abhishek0732** [comment]
But please add day 6 also I will add content in that

**Comment by subhadipbhowmik** [comment]
> But please add day 6 also I will add content in that

Adding Day 6 like OOPS Concept is not good for readers.. Because in day 5 we have covered only till While Do while loops.. I don't think it will be a great idea to add OOPs after Do wile looping concepts..  I will Highly recomend to add contents in existing projects rather adding random Days Content..

**Comment by Abhishek0732** [comment]
Ok i will add, should i delete day 6 before making the pull request or keep it as it is

**Comment by subhadipbhowmik** [comment]
I am Closing this pull request.. Go through the docs folder there i have set questions.. Complete those questions. 
Warning: Don't Just Copy And Paste Code from other site or AI .

**Comment by Abhishek0732** [comment]
ok

**Pull request closed without merging**
