### PR TITLE
Introduction to C++ Fundamentals: Syntax, Structure, and Basic Compon… 

### PR DESCRIPTION
**Pull request by nihasinghania22**
Introduction to C++ Fundamentals: Syntax, Structure, and Basic Components. #526

### CODE REVIEW

**Comment by nihasinghania22** [comment]
Could you please review it? I have added more information in the introduction to CPP section.

**Comment by nihasinghania22** [comment]
@subhadipbhowmik I have added more to the introduction to cpp section. could you please review it.

**Comment by nihasinghania22** [comment]
@subhadipbhowmik Could you please review my pull request

**Comment by subhadipbhowmik** [comment]
> @subhadipbhowmik Could you please review my pull request

Just wait a while

**Comment by nihasinghania22** [comment]
@subhadipbhowmik Could you please generate a Tag for this. My PR that was merged is not being counted.

**Pull request merged**
