### PR TITLE
Want To Add Backend Of Login/Signup Page #191

### PR DESCRIPTION
**Pull request by nishant0708**
Want To Add Backend Of Login/Signup Page #191

-Added backend and Connected with mongodb database

image
replace this text with mongodb uri and it will work

https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/101548649/8c80d34d-dfe2-4cf9-83bb-12ad6bd9af91

**Note:"the error i am getting in this video is from start when i pulled it  I tried to solve it but cant find how to"**

### CODE REVIEW

**Comment by subhadipbhowmik** [comment]
Do not send node_modeles

**Comment by nishant0708** [comment]
Hey @subhadipbhowmik You can check it now it will work fine

**Comment by nishant0708** [comment]
Hey @subhadipbhowmik just asking why this pr is of marked as level 1 because writing backend of anything is definitely not of level 1

**Comment by subhadipbhowmik** [comment]
> Hey @subhadipbhowmik just asking why this pr is of marked as level 1 because writing backend of anything is definitely not of level 1

We appriciate your hard word and dedication. The main focus of our Site is to provide Rich Content.. User login is an optional features for our site.  Looking forward to listen from you.

**Pull request merged**
